services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    volumes:
      - ./src:/app
    expose:
      - 9000

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laraveldb
      MYSQL_USER: laravelpr
      MYSQL_PASSWORD: tosiki
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3366:3366
    volumes:
      - db-test:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmintest
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=laravelpr
      - PMA_PASSWORD=tosiki
    ports:
      - 2929:80

  web:
    container_name: web
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - 8089:80
    depends_on:
      - php
    volumes:
      - ./src:/app
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  db-test:
